(1) CODING OUR FIRST NEURON: 3 INPUTS (ONE NEURON)

In [2]:
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias = 2

outputs = (inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias)

print(outputs)

2.3


(2) CODING OUR SECOND NEURON: 4 INPUTS

In [3]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1]
bias = 2

output = (inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias)
print(output)


4.8


(3) CODING OUR FIRST LAYER

In [5]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

weights1 = weights[0] # LIST OF WEIGHTS ASSOCIATED WITH 1ST NEURON : W11,W12,W13,W14
weights2 = weights[1] # LIST OF WEIGHTS ASSOCIATED WITH 2ND NEURON : W21,W22,W23,W24
weights3 = weights[2] # LIST OF WEIGHTS ASSOCIATED WITH 3RD NEURON : W31,W32,W33,W34

biases = [2,3,0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs =[
    # NEURON 1
    inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
    # NEURON 2
    inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
    # NEURON 3
    inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3
]

print(outputs)

[4.8, 1.21, 2.385]


(4) USING LOOPS FOR BETTER AND EASIER CODING

In [8]:
inputs = [1,2,3,2.5]

# LIST OF WEIGHTS
weights = [[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
# LIST OF BIASES
biases = [2,3,0.5]
# OUTPUT OF CURRENT LAYER
layer_outputs = []



# for each neuron
for neuron_weights,neuron_bias in zip(weights,biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input,weight in zip(inputs,neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron's output variable
        neuron_output += n_input*weight  

    # Add bias
    neuron_output += neuron_bias
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)
print(layer_outputs)





[4.8, 1.21, 2.385]


(6) SINGLE NEURON USING NUMPY

In [9]:
import numpy as np

inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)

# Calculate the dot product and add the bias
outputs = np.dot(weights_array,inputs_array)+bias

print(outputs)

4.8


(7) LAYER OF NEURONS USING NUMPY

In [18]:
import numpy as np

inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

# Calculate the dot product and add the biases
layer_outputs1 = np.dot(weights_array,inputs_array) + biases_array
layer_outputs2 = np.dot(inputs_array,weights_array.T) + biases_array

print(layer_outputs1)
print(layer_outputs2)

[4.8   1.21  2.385]
[4.8   1.21  2.385]


(8) BATCH OF DATA USING NUMPY

NEED TO TAKE TRANSPOSE OF WEIGHT MATRIX

In [ ]:
import numpy as np

inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

# Calculate the dot product and add the biases
outputs = np.dot(inputs_array, weights_array.T) + biases_array
print(outputs)

(9) 2 LAYERS AND BATCH OF DATA USING NUMPY

In [ ]:
import numpy as np

inputs = [[1,2,3,2.5],[2.,5.,-1.,2],[-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]
weights2 = [[0.1,-0.14,0.5],[-0.5,0.12,-0.33],[-0.44,0.73,-0.13]]
biases2 = [-1,2,-0.5]

# CONVERT LISTS TO NUMPY ARRAYS
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# CALCULATE THE OUTPUT OF THE FIRST LAYER
layer1_outputs = np.dot(inputs_array,weights_array.T) + biases_array

# CALCULATE THE OUTPUT OF THE SECOND LAYER
layer2_outputs = np.dot(layer1_outputs,weights2_array.T) + biases2_array

print(layer2_outputs)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
